package com.maintenance.dto.response;

import com.maintenance.enums.MaintenanceStatus;
import lombok.*;
import java.time.LocalDateTime;

@Getter @Setter @Builder @NoArgsConstructor @AllArgsConstructor
public class MaintenanceScheduleResponse {
    private Long id;
    private String scheduleCode;
    private String title;
    private String maintenanceType;
    private String description;
    private LocalDateTime scheduledDate;
    private LocalDateTime actualStartDate;
    private LocalDateTime actualEndDate;
    private Integer estimatedDurationHours;
    private MaintenanceStatus status;
    private Double cost;
    private String notes;
    private Boolean isAutoGenerated;
    private Long deviceId;
    private String deviceName;
    private String deviceCode;
    private Long assignedTechnicianId;
    private String assignedTechnicianName;
    private Long createdById;
    private String createdByName;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
