package com.maintenance.repository;

import com.maintenance.entity.MaintenanceSchedule;
import com.maintenance.enums.MaintenanceStatus;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

@Repository
public interface MaintenanceScheduleRepository extends JpaRepository<MaintenanceSchedule, Long> {

    @Query("SELECT ms FROM MaintenanceSchedule ms WHERE " +
           "(:keyword IS NULL OR LOWER(ms.title) LIKE LOWER(CONCAT('%',:keyword,'%'))) AND " +
           "(:status IS NULL OR ms.status = :status) AND " +
           "(:deviceId IS NULL OR ms.device.id = :deviceId) AND " +
           "(:technicianId IS NULL OR ms.assignedTechnician.id = :technicianId)")
    Page<MaintenanceSchedule> searchSchedules(@Param("keyword") String keyword,
                                              @Param("status") MaintenanceStatus status,
                                              @Param("deviceId") Long deviceId,
                                              @Param("technicianId") Long technicianId,
                                              Pageable pageable);

    List<MaintenanceSchedule> findByDeviceId(Long deviceId);
    List<MaintenanceSchedule> findByStatus(MaintenanceStatus status);
    List<MaintenanceSchedule> findByAssignedTechnicianId(Long technicianId);

    // Lịch quá hạn chưa hoàn thành
    @Query("SELECT ms FROM MaintenanceSchedule ms WHERE ms.scheduledDate < :now AND ms.status = 'SCHEDULED'")
    List<MaintenanceSchedule> findOverdueSchedules(@Param("now") LocalDateTime now);

    // Lịch sắp tới trong N ngày
    @Query("SELECT ms FROM MaintenanceSchedule ms WHERE ms.scheduledDate BETWEEN :now AND :future AND ms.status = 'SCHEDULED'")
    List<MaintenanceSchedule> findUpcomingSchedules(@Param("now") LocalDateTime now, @Param("future") LocalDateTime future);

    // Kiểm tra đã có lịch tự động cho thiết bị chưa
    @Query("SELECT ms FROM MaintenanceSchedule ms WHERE ms.device.id = :deviceId AND ms.isAutoGenerated = true AND ms.status = 'SCHEDULED'")
    List<MaintenanceSchedule> findAutoGeneratedForDevice(@Param("deviceId") Long deviceId);

    @Query("SELECT COUNT(ms) FROM MaintenanceSchedule ms WHERE ms.status = :status")
    long countByStatus(@Param("status") MaintenanceStatus status);

    @Query("SELECT SUM(ms.cost) FROM MaintenanceSchedule ms WHERE ms.status = 'COMPLETED' AND ms.actualEndDate BETWEEN :from AND :to")
    Double sumCostByDateRange(@Param("from") LocalDateTime from, @Param("to") LocalDateTime to);
}
