package com.maintenance.service.impl;

import com.maintenance.dto.request.MaintenanceScheduleRequest;
import com.maintenance.dto.response.MaintenanceScheduleResponse;
import com.maintenance.dto.response.PageResponse;
import com.maintenance.entity.*;
import com.maintenance.enums.DeviceStatus;
import com.maintenance.enums.MaintenanceStatus;
import com.maintenance.exception.ResourceNotFoundException;
import com.maintenance.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.*;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Random;

@Service
@RequiredArgsConstructor
@Slf4j
public class MaintenanceScheduleService {

    private final MaintenanceScheduleRepository scheduleRepository;
    private final DeviceRepository deviceRepository;
    private final UserRepository userRepository;
    private final UserService userService;

    public PageResponse<MaintenanceScheduleResponse> getAll(String keyword, String status, Long deviceId,
                                                            Long technicianId, int page, int size,
                                                            String sortBy, String dir) {
        Sort sort = dir.equalsIgnoreCase("desc") ? Sort.by(sortBy).descending() : Sort.by(sortBy).ascending();
        Pageable pageable = PageRequest.of(page, size, sort);
        MaintenanceStatus ms = parseStatus(status);
        Page<MaintenanceSchedule> result = scheduleRepository.searchSchedules(keyword, ms, deviceId, technicianId, pageable);
        return PageResponse.of(result.map(this::toResponse));
    }

    public MaintenanceScheduleResponse getById(Long id) {
        return toResponse(findById(id));
    }

    @Transactional
    public MaintenanceScheduleResponse create(MaintenanceScheduleRequest request) {
        Device device = deviceRepository.findById(request.getDeviceId())
                .orElseThrow(() -> new ResourceNotFoundException("Device", request.getDeviceId()));

        User currentUser = userService.getCurrentUser();
        User technician = null;
        if (request.getAssignedTechnicianId() != null) {
            technician = userRepository.findById(request.getAssignedTechnicianId())
                    .orElseThrow(() -> new ResourceNotFoundException("Technician", request.getAssignedTechnicianId()));
        }

        String code = "MS-" + DateTimeFormatter.ofPattern("yyyyMMdd").format(LocalDateTime.now())
                + "-" + String.format("%04d", new Random().nextInt(9999));

        MaintenanceSchedule schedule = MaintenanceSchedule.builder()
                .scheduleCode(code)
                .title(request.getTitle())
                .maintenanceType(request.getMaintenanceType())
                .description(request.getDescription())
                .scheduledDate(request.getScheduledDate())
                .estimatedDurationHours(request.getEstimatedDurationHours())
                .status(MaintenanceStatus.SCHEDULED)
                .cost(request.getCost() != null ? request.getCost() : 0.0)
                .notes(request.getNotes())
                .isAutoGenerated(false)
                .device(device)
                .assignedTechnician(technician)
                .createdBy(currentUser)
                .build();

        return toResponse(scheduleRepository.save(schedule));
    }

    @Transactional
    public MaintenanceScheduleResponse update(Long id, MaintenanceScheduleRequest request) {
        MaintenanceSchedule schedule = findById(id);

        schedule.setTitle(request.getTitle());
        if (request.getMaintenanceType() != null) schedule.setMaintenanceType(request.getMaintenanceType());
        if (request.getDescription() != null) schedule.setDescription(request.getDescription());
        if (request.getScheduledDate() != null) schedule.setScheduledDate(request.getScheduledDate());
        if (request.getEstimatedDurationHours() != null) schedule.setEstimatedDurationHours(request.getEstimatedDurationHours());
        if (request.getCost() != null) schedule.setCost(request.getCost());
        if (request.getNotes() != null) schedule.setNotes(request.getNotes());

        if (request.getStatus() != null) {
            schedule.setStatus(request.getStatus());
            if (request.getStatus() == MaintenanceStatus.IN_PROGRESS) {
                schedule.setActualStartDate(LocalDateTime.now());
                schedule.getDevice().setStatus(DeviceStatus.UNDER_MAINTENANCE);
                deviceRepository.save(schedule.getDevice());
            }
            if (request.getStatus() == MaintenanceStatus.COMPLETED) {
                schedule.setActualEndDate(LocalDateTime.now());
                schedule.getDevice().setStatus(DeviceStatus.ACTIVE);
                deviceRepository.save(schedule.getDevice());
            }
        }

        if (request.getActualStartDate() != null) schedule.setActualStartDate(request.getActualStartDate());
        if (request.getActualEndDate() != null) schedule.setActualEndDate(request.getActualEndDate());

        if (request.getAssignedTechnicianId() != null) {
            User tech = userRepository.findById(request.getAssignedTechnicianId())
                    .orElseThrow(() -> new ResourceNotFoundException("Technician", request.getAssignedTechnicianId()));
            schedule.setAssignedTechnician(tech);
        }

        return toResponse(scheduleRepository.save(schedule));
    }

    @Transactional
    public MaintenanceScheduleResponse complete(Long id, Double cost, String notes) {
        MaintenanceSchedule schedule = findById(id);
        schedule.setStatus(MaintenanceStatus.COMPLETED);
        schedule.setActualEndDate(LocalDateTime.now());
        if (cost != null) schedule.setCost(cost);
        if (notes != null) schedule.setNotes(notes);
        schedule.getDevice().setStatus(DeviceStatus.ACTIVE);
        deviceRepository.save(schedule.getDevice());
        return toResponse(scheduleRepository.save(schedule));
    }

    @Transactional
    public void delete(Long id) {
        if (!scheduleRepository.existsById(id)) throw new ResourceNotFoundException("MaintenanceSchedule", id);
        scheduleRepository.deleteById(id);
    }

    public List<MaintenanceScheduleResponse> getUpcoming(int days) {
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime future = now.plusDays(days);
        return scheduleRepository.findUpcomingSchedules(now, future)
                .stream().map(this::toResponse).toList();
    }

    public List<MaintenanceScheduleResponse> getOverdue() {
        return scheduleRepository.findOverdueSchedules(LocalDateTime.now())
                .stream().map(this::toResponse).toList();
    }

    // ====== AUTO SCHEDULER (chạy mỗi ngày lúc 8:00 AM) ======
    @Scheduled(cron = "0 0 8 * * ?")
    @Transactional
    public void autoGenerateMaintenanceSchedules() {
        log.info("=== Auto generating maintenance schedules ===");
        List<Device> devices = deviceRepository.findAllWithMaintenanceCycle();
        for (Device device : devices) {
            if (device.getStatus() == DeviceStatus.DISPOSED) continue;
            // Kiểm tra đã có lịch tự động chưa
            List<MaintenanceSchedule> existing = scheduleRepository.findAutoGeneratedForDevice(device.getId());
            if (!existing.isEmpty()) continue;

            LocalDateTime nextMaintenance = LocalDateTime.now().plusDays(device.getMaintenanceCycleDays());
            String code = "AUTO-" + device.getDeviceCode() + "-"
                    + DateTimeFormatter.ofPattern("yyyyMMdd").format(nextMaintenance);

            MaintenanceSchedule schedule = MaintenanceSchedule.builder()
                    .scheduleCode(code)
                    .title("Bảo trì định kỳ - " + device.getName())
                    .maintenanceType("Định kỳ")
                    .description("Lịch bảo trì tự động sinh cho thiết bị " + device.getName())
                    .scheduledDate(nextMaintenance)
                    .status(MaintenanceStatus.SCHEDULED)
                    .cost(0.0)
                    .isAutoGenerated(true)
                    .device(device)
                    .build();
            scheduleRepository.save(schedule);
            log.info("Auto generated schedule for device: {}", device.getDeviceCode());
        }
    }

    // Cập nhật quá hạn mỗi giờ
    @Scheduled(cron = "0 0 * * * ?")
    @Transactional
    public void markOverdueSchedules() {
        List<MaintenanceSchedule> overdue = scheduleRepository.findOverdueSchedules(LocalDateTime.now());
        overdue.forEach(s -> s.setStatus(MaintenanceStatus.OVERDUE));
        scheduleRepository.saveAll(overdue);
        if (!overdue.isEmpty()) log.info("Marked {} schedules as OVERDUE", overdue.size());
    }

    private MaintenanceSchedule findById(Long id) {
        return scheduleRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("MaintenanceSchedule", id));
    }

    private MaintenanceStatus parseStatus(String s) {
        if (s == null || s.isEmpty()) return null;
        try { return MaintenanceStatus.valueOf(s); } catch (Exception e) { return null; }
    }

    public MaintenanceScheduleResponse toResponse(MaintenanceSchedule ms) {
        return MaintenanceScheduleResponse.builder()
                .id(ms.getId())
                .scheduleCode(ms.getScheduleCode())
                .title(ms.getTitle())
                .maintenanceType(ms.getMaintenanceType())
                .description(ms.getDescription())
                .scheduledDate(ms.getScheduledDate())
                .actualStartDate(ms.getActualStartDate())
                .actualEndDate(ms.getActualEndDate())
                .estimatedDurationHours(ms.getEstimatedDurationHours())
                .status(ms.getStatus())
                .cost(ms.getCost())
                .notes(ms.getNotes())
                .isAutoGenerated(ms.getIsAutoGenerated())
                .deviceId(ms.getDevice() != null ? ms.getDevice().getId() : null)
                .deviceName(ms.getDevice() != null ? ms.getDevice().getName() : null)
                .deviceCode(ms.getDevice() != null ? ms.getDevice().getDeviceCode() : null)
                .assignedTechnicianId(ms.getAssignedTechnician() != null ? ms.getAssignedTechnician().getId() : null)
                .assignedTechnicianName(ms.getAssignedTechnician() != null ? ms.getAssignedTechnician().getFullName() : null)
                .createdById(ms.getCreatedBy() != null ? ms.getCreatedBy().getId() : null)
                .createdByName(ms.getCreatedBy() != null ? ms.getCreatedBy().getFullName() : null)
                .createdAt(ms.getCreatedAt())
                .updatedAt(ms.getUpdatedAt())
                .build();
    }

    // --- BỔ SUNG THEO YÊU CẦU ---

    @Transactional
    public MaintenanceScheduleResponse approve(Long id, Long technicianId) {
        MaintenanceSchedule ms = findById(id);
        User tech = userRepository.findById(technicianId)
                .orElseThrow(() -> new ResourceNotFoundException("User", technicianId));

        // Giao việc cho Kỹ thuật viên
        ms.setAssignedTechnician(tech);
        // Trạng thái vẫn là SCHEDULED nhưng đã có người chịu trách nhiệm
        return toResponse(scheduleRepository.save(ms));
    }

    @Transactional
    public MaintenanceScheduleResponse execute(Long id) {
        MaintenanceSchedule ms = findById(id);

        // Cập nhật trạng thái lịch bảo trì
        ms.setStatus(MaintenanceStatus.IN_PROGRESS);
        ms.setActualStartDate(LocalDateTime.now());

        // Đồng bộ trạng thái thiết bị sang "Đang bảo trì"
        if (ms.getDevice() != null) {
            ms.getDevice().setStatus(DeviceStatus.UNDER_MAINTENANCE);
            deviceRepository.save(ms.getDevice());
        }

        return toResponse(scheduleRepository.save(ms));
    }
}